### ISSUE TITLE
black viewer

### ISSUE THREAD

**Issue by yvanblanchard** [kovacsv/VisualScriptEngineWeb#19]
Hello,

I tried the Live version, but I can't see anything in viewer (black window) : (using Firefox browser on Win10)
![image](https://user-images.githubusercontent.com/63931618/170486225-5cc113b9-3e2a-4498-9fa7-0fcd01b003a5.png)

**Comment by kovacsv** [comment]
Probably the reason was the same as here: https://github.com/kovacsv/Online3DViewer/issues/269.
