### ISSUE TITLE
Notify the user about unsaved changes when leaving the site

### ISSUE THREAD

**Issue by kovacsv** [kovacsv/VisualScriptEngineWeb#6]
Warning in these cases:
- Leaving the site.
- New file.
- Opening another file.

**Comment by kovacsv** [comment]
This is the default confirmation dialog what Chrome provides:
![image](https://user-images.githubusercontent.com/2034315/91483882-a6def200-e8a8-11ea-977f-d2d096f067c8.png)

It's not possible to modify button's text.

**Comment by Gaschitz** [comment]
![Save Warning](https://user-images.githubusercontent.com/57147683/92388934-5ec99600-f118-11ea-86a9-05aa5c47e06b.png)
